apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ipocket.fullname" . }}-secrets
  labels:
    app.kubernetes.io/name: {{ include "ipocket.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
stringData:
  SESSION_SECRET: {{ .Values.sessionSecret | quote }}
  ADMIN_BOOTSTRAP_USERNAME: {{ .Values.adminBootstrap.username | quote }}
  ADMIN_BOOTSTRAP_PASSWORD: {{ .Values.adminBootstrap.password | quote }}
